name: MeowApp
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"

packages:
  MeowCore:
    path: ../MeowCore

targets:
  MeowApp:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.meow.sim
        SWIFT_VERSION: 5.10
        INFOPLIST_FILE: Sources/App/Info.plist
    dependencies:
      - package: MeowCore
        product: MeowFeatures
      - package: MeowCore
        product: MeowData

schemes:
  MeowApp:
    build:
      targets:
        MeowApp: all
    run:
      config: Debug
